name: Chiaranai_foodapp
description: "Flutter food ordering app with Firebase, Map, and YouTube"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---------- Firebase ----------
  firebase_core: ^2.24.2
  cloud_firestore: ^4.17.5

  # ---------- Network / API ----------
  http: ^0.13.6
  url_launcher: ^6.2.5

  # ---------- Video ----------
  video_player: ^2.8.2
  youtube_player_flutter: ^9.1.3

  # ---------- Location & Map ----------
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

  # ---------- UI ----------
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/1.jpg
    - assets/2.png
    - assets/3.jpg
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/heart.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/heart.png
